### All livreur
GET http://localhost:8080/Smart_Delivery/api/livreurs
### livreur by id
GET http://localhost:8080/Smart_Delivery/api/livreurs/1

### Create livreur
POST http://localhost:8080/Smart_Delivery/api/livreurs
Content-Type: application/json

{
      "nom": "ismail",
      "prenom": "baoud",
      "vehicule": "walo",
      "telephone": "0698765432"
}
### Update livreur
PUT http://localhost:8080/Smart_Delivery/api/livreurs/3
Content-Type: application/json

{
      "nom": "ISMAIL",
      "prenom": "BAOUD",
      "vehicule": "walo",
      "telephone": "0698765432"
}
### Delete livreur
DELETE http://localhost:8080/Smart_Delivery/api/livreurs/1


### All Colis
GET http://localhost:8080/Smart_Delivery/api/colis
### Colis by id
GET http://localhost:8080/Smart_Delivery/api/colis/4
### Create Colis
POST http://localhost:8080/Smart_Delivery/api/colis?idLivreur=3
Content-Type: application/json

{
  "adresse": "255 Mohammed V, Casablanca",
  "destinataire": "houssam houssam",
  "poids": 25
}

### Update Colis
PUT http://localhost:8080/Smart_Delivery/api/colis/3
Content-Type: application/json

{
  "statut": "EN_TRANSIT"
}
### Delete Colis
DELETE http://localhost:8080/Smart_Delivery/api/colis/4
